config/routes.rb
DevpointLabs::Application.routes.draw do
  
  resources :admin, only: :index 
  namespace :admin do
    resources :users
  end

  resources :posts

  resources :projects do
    get 'pictures/new', to: 'projects#new_picture', as: :new_picture
    post 'pictures/new', to: 'projects#create_picture', as: :create_picture
  end
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root :to => 'static_pages#home'
  get "path", to: 'controller#action', as: :name_of_path

  get "web-development", to: "static_pages#web_development", as: :web_development
  get "about", to: "static_pages#about", as: :about
  get "ios-development", to: "static_pages#ios_development", as: :ios_development
  get "utah", to: "static_pages#utah", as: :utah
  get "learn-more", to: "static_pages#learn_more", as: :learn_more
  get "tuition", to: "static_pages#tuition", as: :tuition
  get "faq", to: "static_pages#faq", as: :faq

  get "contact-us", to: 'contact#new', as: :contact
  post "contact-us", to: 'contact#create', as: :contact

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  has_many :tags, as: :taggable, dependent: :destroy
  has_many :pictures, as: :pictureable, dependent: :destroy
  accepts_nested_attributes_for :pictures, :tags
  attr_accessible :completed_at, :description, :name, :published_at, :stats, :url, :user_id, :pictures_attributes, :tags_attributes

  validates :name, :description, :user_id, presence: true
  validates :user, associated: true

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_filter :find_users, only: [:new, :edit, :create, :update]  
  # GET /projects
  # GET /projects.json
  def index
    @projects = ProjectDecorator.decorate_collection(Project.includes(:pictures, :user))
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
      format.xml { render xml: @projects}
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id], include: [:pictures, :user, :tags]).decorate

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
      format.js
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = current_user.object.projects.new
    @project.pictures.build 
    @project.tags.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = ProjectDecorator.find(params[:id])

  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.object.projects.new(params[:project])
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        flash.now.alert = "Your Project could not be created. Please check the errors below"
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        flash.now.alert = "Project could not be updated. Please correct the errors below."
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url, notice: "That project is gone!" }
      format.json { head :no_content }
    end
  end

  def new_picture
    @project = ProjectDecorator.find(params[:project_id])
    @picture = @project.object.pictures.new
  end

  def create_picture
    @project = ProjectDecorator.find(params[:project_id])
    @picture = @project.object.pictures.new(params[:picture])
    if @picture.save
      redirect_to project_path(@project), notice: "Image successfully uploaded"
    else
      flash.now.alert = 'Image could not be saved. See errors below'
      render :new_picture
    end
  end  

  private
  def find_users
    @users = UserDecorator.decorate_collection(User.order('first_name desc'))
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description, input_html: {rows: 6} %>
    <%= f.input :url %>
    <%= f.input :completed_at, include_blank: true %>
    <%= f.input :published_at, include_blank: true %>
    <%= f.input :stats, input_html: {rows: 6} %>
    <%= f.association :user, collection: @users.collect {|user| [ user.full_name, user.id ] } %>
    <h3> Upload a cover image </h3>
    <div class ="photo-upload">
      <%= f.simple_fields_for :pictures do |p| %>
        <%= render "picture_fields", :f => p %> 
        <div class='links'>
          <%= link_to_add_association 'Add More Pictures', f, :pictures, :class => "btn btn-success" %>
        </div>
      <% end %>
    </div>
    <h3> Add a tag</h3>
    <div class="tasks">
      <%= f.simple_fields_for :tags do |tag| %>
        <%= render "tag_fields", :f => tag %>
        <div class='links'>
          <%= link_to_add_association 'Add More Tags', f, :tags, :class => "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/projects/_picture_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-xs-4"><%= f.input :image %></div>
    <div class="col-xs-8"><%= f.input :caption %></div>
    <div class="col-xs-12"><%= f.input :description, input_html: {rows: 3}%></div>
    <div class="col-xs-2 col-md-offset-10"><%= link_to_remove_association "Remove Photo", f, :class => "btn btn-danger" %></div>
  </div>
</div>

app/views/projects/_project_modal.html.erb
<div class="modal fade" id="project-<%=project.id %>"  role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">
            &nbsp;
            <%= link_to 'Edit Project', edit_project_path(project) if can? :edit, project %>
          </h4>

      </div>
      <div class="modal-body">
        <div class='row'>
          <div class='col-sm-6 text-center'>
            <%= image_tag project.pictures.first.image.url(:large), class: 'featured-image img-responsive img-thumbnail' if project.pictures.present? %>
          </div>
          <div class='col-sm-6'>
            <h2><%= project.name.titleize %></h2>
            <h3>By: <%= project.user.try(:full_name).titleize %></h3>
            <%= display_tags(project) %>
            <p><%= simple_format project.description %></p>
            <hr>
            <p>Completed <%= human_date project.completed_at %></p>
          </div>          
        </div>
        <hr>
        <div class='project-thumbnails'>
          <% project.pictures.each do |pic| %>
            <%= image_tag(pic.image.url(:thumb), class: 'img-responsive img-thumbnail', data: { url:  pic.image.url(:large) } )%>
          <% end %>
        </div>
      </div>
      <div class="modal-footer text-center">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/projects/_tag_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-xs-4"><%= f.input :name, label: false, placeholder: 'Name'  %></div>
    <div class="col-xs-4"><%= link_to_remove_association "Remove Tag", f, :class => "btn btn-danger" %></div>
  </div>
</div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class='page-header'>
  <h1> Our Projects</h1>
</div>
<div class='project-info'></div>
<div class='row'>
  <% @projects.each do |project| %>
    <div class='project-tile col-xs-6 col-sm-4 col-md-3 no-gutters' >
      <div class='project-title'>
        <h4><%= project.name.try(:titleize) %></h4>
        <p><%= project.user.try(:full_name) %></p>
        <p>
          <%= link_to "Show More >", project_path(project), remote: true %>
        </p>
      </div>
      <%= image_tag project.pictures.first.image.url(:medium), class: 'img-responsive' if project.pictures.present? %>
    </div>
  <% end %>
</div>
<% if can? :create, Project %>
  <p class='pull-right'>
    <%= link_to "Create New Project", new_project_path, class: 'btn btn-lg btn-primary' %>
  </p>
<% end %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/new_gallery_image.html.erb
<%= simple_form_for @picture, url: project_create_picture_path(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.input :image, required: true %>
  <%= f.input :caption %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/projects/new_picture.html.erb
<%= simple_form_for @picture, url: project_create_picture_path(@project) do |f| %>
  <%= f.error_notification %>
  <%= f.input :image, required: true %>
  <%= f.input :caption %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/projects/show.html.erb
<div class='row'>
  <div class='col-sm-4'>
    <%= image_tag @project.pictures.first.image.url(:medium) if @project.pictures.present? %>
    <ul class='list-inline thumbnails'>
      <% @project.pictures.each do |picture| %>
        <li class='thumbnail text-center'>
          <p><%= image_tag(picture.image.url(:thumb), class: 'img-circle') %></p>
          </li>
      <% end %>
    </ul>
    <%= display_tags(@project) %>
  </div>
  <div class='col-sm-8'>
  <div class='page-header'>
    <h1>
      <%= @project.name %>
      <small><%= link_to @project.url, @project.url %></small>
    </h1>
    <h2><%= @project.user.full_name %></h2>
    <% if @project.completed_at.present? %>
      <p><b>Completed</b>  <%= human_date @project.completed_at %></p>
    <% end %>
    <% if @project.published_at.present? %>
      <p><b>Published at</b>  <%= human_date @project.published_at %></p>
    <% end %>

    <p><%= simple_format @project.description %></p>
    <% if @project.stats.present? %>
    <h4>Stats:</h4>
    <p><%= simple_format @project.stats %></p>
    <% end %>
    <div id="gallery-carousel" class="carousel slide">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <% @project.pictures.each_with_index do |picture, index| %>
          <li data-target="#gallery-carousel" data-slide-to="<%= index %>" class="<%= 'active' if index == 0 %>"></li>
        <% end %>
      </ol>

      <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <% @project.pictures.each_with_index do |picture, index| %>
          <div class="item text-center <%= 'active' if index == 0 %>">
            <%= image_tag picture.image.url(:large), class: 'image-responsive' %>
            <div class="carousel-caption">
              <%= picture.caption %>
            </div>
          </div>
        <% end %>
      </div>

      <!-- Controls -->
      <a class="left carousel-control" href="#gallery-carousel" data-slide="prev">
        <span class="icon-prev"></span>
      </a>
      <a class="right carousel-control" href="#gallery-carousel" data-slide="next">
        <span class="icon-next"></span>
      </a>
    </div>    
  </div>
</div>

<hr />


<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>