config/routes.rb
DevpointLabs::Application.routes.draw do
  
  resources :admin, only: :index 
  namespace :admin do
    resources :users
  end

  resources :posts

  resources :projects do
    get 'pictures/new', to: 'projects#new_picture', as: :new_picture
    post 'pictures/new', to: 'projects#create_picture', as: :create_picture
  end
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root :to => 'static_pages#home'
  get "path", to: 'controller#action', as: :name_of_path

  get "web-development", to: "static_pages#web_development", as: :web_development
  get "about", to: "static_pages#about", as: :about
  get "ios-development", to: "static_pages#ios_development", as: :ios_development
  get "utah", to: "static_pages#utah", as: :utah
  get "learn-more", to: "static_pages#learn_more", as: :learn_more
  get "tuition", to: "static_pages#tuition", as: :tuition
  get "faq", to: "static_pages#faq", as: :faq

  get "contact-us", to: 'contact#new', as: :contact
  post "contact-us", to: 'contact#create', as: :contact

end

app/models/user.rb
  # user: { first_name: 'test', ......, picture_attributes: { attributes} }
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_one :picture, as: :pictureable, dependent: :destroy
  accepts_nested_attributes_for :picture
  has_many :projects, dependent: :destroy
  has_many :tags, as: :taggable, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :avatar, :picture_attributes, :provider, :uid
  validates :first_name, :last_name, presence: true
  after_create :send_welcome_email 

  def setup_twitter_user(auth)
    self.first_name, self.last_name = auth.info.name.split(' ')
    self.provider = auth.provider
    self.uid = auth.uid
    self.password = Devise.friendly_token[0,20]
    self.picture.image = auth.info.image
  end

  private
  
  def send_welcome_email 
    UserMailer.welcome(self).deliver
  end
  

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    user ||= User.new() 
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < AdminController
  # GET /admin/users
  # GET /admin/users.json
  def index
    @users = UserDecorator.decorate_collection(User.includes(:picture, :tags, :projects))

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /admin/users/1
  # GET /admin/users/1.json
  def show
    @user = UserDecorator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/new
  # GET /admin/users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /admin/users/1/edit
  def edit
    @user = UserDecorator.find(params[:id])
  end

  # POST /admin/users
  # POST /admin/users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        flash.now.alert = "Could not create User, please check for errors."
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /admin/users/1
  # PUT /admin/users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to admin_user_path(@user), notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        flash.now.alert = "Could not update User, please check for errors."
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/users/1
  # DELETE /admin/users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: "User successfully deleted." }
      format.json { head :no_content }
    end
  end
end

app/views/admin/users/_form.html.erb
<%= simple_form_for([:admin, @user]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/admin/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>

app/views/admin/users/index.html.erb
<h1>Listing Users</h1>

<table>
  <tr>
    <th>First Name</th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.first_name %> </td>
    <td><%= link_to 'Show', admin_user_path(user) %></td>
    <td><%= link_to 'Edit', edit_admin_user_path(user) %></td>
    <td><%= link_to 'Destroy', admin_user_path(user), method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_admin_user_path %>

app/views/admin/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_users_path %>

app/views/admin/users/show.html.erb
<% if @user.picture %>
  <p><%= image_tag(@user.picture.image.url(:small), class: 'img-circle') %></p>
<% end %>
<h3> <%= @user.full_name %></h3>
<p>Member since: <%= @user.created_at %></p>
<%= display_tags(@user) %>
<p>Projects</p>
<ul>
  <% @user.projects.each do |p| %>
    <li><%= p.name %></li>
  <% end %>
</ul>

<%= link_to 'Edit', edit_admin_user_path(@user) %> |
<%= link_to 'Back', admin_users_path %>