config/routes.rb
DevpointLabs::Application.routes.draw do
  
  resources :admin, only: :index 
  namespace :admin do
    resources :users
  end

  resources :posts

  resources :projects do
    get 'pictures/new', to: 'projects#new_picture', as: :new_picture
    post 'pictures/new', to: 'projects#create_picture', as: :create_picture
  end
  devise_for :users, controllers: {registrations: 'registrations', omniauth_callbacks: 'omniauth_callbacks'}

  root :to => 'static_pages#home'
  get "path", to: 'controller#action', as: :name_of_path

  get "web-development", to: "static_pages#web_development", as: :web_development
  get "about", to: "static_pages#about", as: :about
  get "ios-development", to: "static_pages#ios_development", as: :ios_development
  get "utah", to: "static_pages#utah", as: :utah
  get "learn-more", to: "static_pages#learn_more", as: :learn_more
  get "tuition", to: "static_pages#tuition", as: :tuition
  get "faq", to: "static_pages#faq", as: :faq

  get "contact-us", to: 'contact#new', as: :contact
  post "contact-us", to: 'contact#create', as: :contact

end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissable alert-<%= name == :notice ? "success" : "danger" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "DevPoint Labs", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to t(:web_development), web_development_path %></li>
      <li><%= link_to t(:about), about_path %></li>
      <li><%= link_to t(:utah), utah_path %></li>
      <li><%= link_to t(:learn_more), learn_more_path %></li>
      <li><%= link_to t(:tuition), tuition_path %></li>
      <li><%= link_to t(:faq), faq_path %></li>
      <li><%= link_to t(:projects), projects_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li> 
          <%= link_to edit_user_registration_path do %>
            <%# image_tag current_user.picture.url(:mini), class: 'img-circle'  %> 
            <%= current_user.full_name %>
          <% end %>
        </p> 
        </li>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
        <li><%= link_to "Sign Up", new_user_registration_path %></li> 
        <li><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class='fa-flag'></i>&nbsp; <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="?locale=en">English</a></li>
          <li><a href="?locale=es">Español</a></li>
        </ul>
      </li>
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= content_for?(:title) ? yield(:title) + " | DevPoint Labs" : "DevPoint Labs"  %></title>
    <meta name='description' content="<%= content_for?(:description) ? yield(:description) : 'DevPoint Labs is an intense 11 week bootcamp for Ruby on Rails Web Development and iOS mobile development.' %> " >
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
  </head>
  <body>

    <%= render 'layouts/navigation' %>    
    <div class='container'>
      <%= render 'layouts/messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/email.html.erb
<html>
  <head>
    <title>*|MC:SUBJECT|*</title>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    
  <style type="text/css">
    body,#wrap{
      background-color:#d2efef;
      text-align:center;
    }
    #layout{
      margin:10px auto;
      text-align:left;
    }
    #topbar{
      background-color:transparent;
      padding:10px 0 20px;
      color:#666;
      font-size:11px;
      font-family:Georgia;
      font-weight:normal;
      text-align:center;
    }
    #topbar{
      color:#ff8e6b;
      text-decoration:underline;
      font-weight:normal;
    }
    #content{
      background:#ffffff;
      line-height:1.25em;
      padding:10px 20px 30px 40px;
      vertical-align:top;
    }
    .primary-heading{
      font-size:22px;
      font-weight:normal;
      color:#7e7e7e;
      font-family:Georgia;
      line-height:150%;
      text-align:center;
    }
    p.btn{
      background:#ff8e6b;
      border:3px solid #ebebeb;
      width:auto;
      color:#fff;
      text-align:center;
      margin:25px 15%;
      font-size:40px;
      font-family:Georgia;
      padding:.7em 0;
    }
    p.note{
      font-family:Georgia;
      color:#777;
      margin:0 10%;
      font-size:16px;
      line-height:1.4em;
      text-align:center;
    }
    #footer{
      background-color:transparent;
      padding:20px;
      font-size:10px;
      color:#666;
      line-height:100%;
      font-family:Georgia;
      text-align:center;
    }
    #footer a{
      color:#ff8e6b;
      text-decoration:underline;
      font-weight:normal;
    }
    a,a:link,a:visited{
      color:#ff8e6b;
      text-decoration:underline;
      font-weight:normal;
    }
</style></head>
  <body style="background-color: #d2efef;text-align: center;">
    <div id="wrap" style="background-color: #d2efef;text-align: center;">
      <table id="layout" border="0" cellspacing="0" cellpadding="0" width="600" style="margin: 10px auto;text-align: left;">
        <tr>
          <td id="topbar" style="background-color: transparent;padding: 10px 0 20px;color: #ff8e6b;font-size: 11px;font-family: Georgia;font-weight: normal;text-align: center;text-decoration: underline;"><!-- *|END:IF|* --></td>
        </tr>
        <tr>
          <td>
            <h1> DevPoint Labs</h1>
          </td>
        </tr>
        <tr>
          <td id="content" style="background: #ffffff;line-height: 1.25em;padding: 10px 20px 30px 40px;vertical-align: top;">
            <%= yield %>
</td>
        </tr>
        <tr>
          <td id="page_curl">
            <img src="http://gallery.mailchimp.com/0d61bb2ec9002f0e9872b8c36/images/beauty_coupon_footer.png">
          </td>
        </tr>
        <tr>
          <td id="footer" style="background-color: transparent;padding: 20px;font-size: 10px;color: #666;line-height: 100%;font-family: Georgia;text-align: center;">
              <p>Copyright &copy; <%= Time.now.year %> DevPoint Labs All rights reserved.</p>
          </td>
        </tr>
      </table>
    </div>
    <span style="padding: 0px;"></span>
  </body>
</html>